### PR TITLE
Better errors

### PR DESCRIPTION
**Pull request by brandoncash**
Makes error messages easier to read. Introduces `cli-color` to allow colors in the terminal.

Example output:
Screenshot

Totally down for this being a jumping-off point to a more consistent and eye-appealing method throughout our tools.

Here's the original output:
Original

### CODE REVIEW

**Comment by prichey** [comment]
My success message is colored differently from yours for some reason. Not that this is necessarily a bad thing, but I'm curious why yours is green and mine isn't. 

screenshot 2016-05-10 11 48 09

**Comment by prichey** [comment]
`clc.white.bgGreen` seems to work for me but `clc.white.bgGreenBright` doesn't. Wondering if anybody else gets the same thing with their current terminal config.

screenshot 2016-05-10 11 54 38

**Comment by prichey** [comment]
Not that this is warranted just because I had issues with the green above, but wondering if you checked out https://github.com/marak/colors.js/? It has lots more stars and has a cool api where you can set up a theme and define a 'warning' color, for example, and just use that rather than remembering which shade you used for warnings earlier. https://github.com/marak/colors.js/#custom-themes 

Just something to consider. 😄

**Comment by brandoncash** [comment]
Super weird that it'd be not green; my guess is that you just have an odd color for bright green in your terminal. You'll probably get the same result from other libraries as they should just print out the color codes.

`colors.js` looks nice! The theme would be great to expose to `_config.js` so people can change it to fit their preferences. There is likely a way to do that with `cli-color` but I'm up for swapping it out for `colors.js`.

**Comment by prichey** [comment]
Confirming that my color profile is wonky. ¯_(ツ)_/¯

screenshot 2016-05-10 13 21 39

**Comment by brandoncash** [comment]
First attempt at using `colors.js` - while the themes are really nice, it doesn't seem possible to use bright colors as backgrounds. But it does come with zalgo, so there's that...
With colors.js

**Comment by prichey** [comment]
I think the non-bright colors look good. Interesting that you can't use them though.

**Comment by chadwatson** [comment]
I added an option to get Notification Center updates when there are Sass compile errors. It used to be in Gulp Eta, and figured some people probably liked it.

**Comment by prichey** [comment]
Looks like warnings fall through without getting color treated. Working on a fix for this. 
screenshot 2016-05-16 16 45 23

**Comment by prichey** [comment]
Turns out that this is more difficult than I thought. 

It is possible (via a recent experimental feature: https://github.com/sass/node-sass#functions--v300---experimental) to add custom functions to handle `@warn` and `@debug` output, but only the value of the message is exposed, so the file path and line number are both lost. In my opinion, this isn't a reasonable compromise to simply style the message like the success / error output. 

Closing this issue for now, will revisit at a later point to see if this is more feasible.

For more info, here's some discussion on the `node-sass` repo (https://github.com/sass/node-sass/issues/646#issuecomment-87121010) which references this discussion on `libsass` (https://github.com/sass/libsass/issues/1037).

**Comment by prichey** [comment]
Accidentally closed. Reopening. (Sorry!)

**Pull request merged**
